### PR TITLE
fix: remove strictMode option

### LINKED ISSUE #1854: Remove strictMode config option
https://github.com/isaachinman/next-i18next/discussions/1853#discussion-4120121

### PR DESCRIPTION
**Pull request by proalgor**
fixes #1854

### CODE REVIEW

**Review by isaachinman — CHANGES_REQUESTED** [review]
There are three other files that `strictMode` needs to be removed from.

**Comment by proalgor** [comment]
> There are three other files that `strictMode` needs to be removed from.

Updated

**Comment by isaachinman** [comment]
Looks good. Please add a semantic title.

**Comment by proalgor** [comment]
> Looks good. Please add a semantic title.

Done

**Review by isaachinman — APPROVED** [review]

**Comment by isaachinman** [comment]
Thanks @proalgor!

**Pull request merged**
