### PR TITLE
fix: resources of configOverride doesn't work

### PR DESCRIPTION
**Pull request by rubayethossain**
This PR fixes issue #1603

### CODE REVIEW

**Review by isaachinman — COMMENTED** [review]
Can you include test coverage for this bug fix?

**Comment by isaachinman** [comment]
@rubayethossain Are you able to carry on with this PR, or would you like me to take over?

**Comment by rubayethossain** [comment]
Hi @isaachinman I would like to add the test coverage. However I am not so familiar with test, so would be great if you can take over. 

Thank you!

**Comment by isaachinman** [comment]
Thanks @rubayethossain!

**Pull request closed without merging**
