### PR TITLE
feat: Add section `module` for bundle detect to use es module

### PR DESCRIPTION
**Pull request by NamPNQ**
Add section `module` for bundle detect to use es module

### CODE REVIEW

**Comment by felixmosh** [comment]
Check this [out](https://github.com/isaachinman/next-i18next/pull/409)

**Comment by isaachinman** [comment]
What's the `@babel/proposal-class-properties` plugin's role here?

**Comment by NamPNQ** [comment]
Add this role for fix https://circleci.com/gh/isaachinman/next-i18next/1153

**Comment by isaachinman** [comment]
This will break support for IE11 and older browser targets.

NextJs is moving towards transpilation of deps, which is great, but as far as I know we're not quite there yet.

**Comment by NamPNQ** [comment]
@issachinman I dont know why it break IE11

**Comment by NamPNQ** [comment]
@isaachinman As you have done for version 8, please also support v7

https://github.com/isaachinman/next-i18next/pull/965/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R11

**Pull request closed without merging**
