### PR TITLE
fix: generate types using tsc and stop shipping the /src directory

### PR DESCRIPTION
**Pull request by stevejhiggs**
By using typescripts declaration mode we can generate d.ts files for all of the relevant types and stop shipping the /src directory

fix for https://github.com/isaachinman/next-i18next/issues/1026

### CODE REVIEW

**Comment by isaachinman** [comment]
Hey @stevejhiggs, looks good! Mind fixing up the conflict?

**Comment by stevejhiggs** [comment]
Done! I had a few issues with a duplicate import of i18n that seems to have been introduced after the last PR merge. I've fixed the duplicate by renaming it in the same way as in ./appwithTranslation

**Comment by isaachinman** [comment]
Looks good. Can we delete [this file](https://github.com/isaachinman/next-i18next/blob/master/serverSideTranslations.d.ts) as well?

**Comment by stevejhiggs** [comment]
I had left that alone as I was unsure as to why both the serverSideTranslations.js + d.ts existed in the root directory. The export from /src/index.ts would seem to cover all the import use cases.

Happy to get rid of both if you do not think they are needed

**Comment by daniel-stockman-lark** [comment]
@stevejhiggs @isaachinman `serverSideTranslations.d.ts` is necessary to support `import { serverSideTranslations } from 'next-i18next/serverSideTranslations'`, so it should be updated to point to the new types output location `dist/types/serverSideTranslations`. (the package.json `types` definition doesn't cover this explicit subpath, only `main`)

```patch
-export { serverSideTranslations } from './src/serverSideTranslations'
+export { serverSideTranslations } from './dist/types/serverSideTranslations'
```

**Comment by stevejhiggs** [comment]
@daniel-stockman-lark ah I see. My mistake, I misread the docs and thought that entry point was not used. I've made the change you suggested.

**Comment by isaachinman** [comment]
Yeah that's correct – `serverSideTranslations` needs to be a separate entry point as it consumes NodeJs modules like `fs` and needs to be stripped from client bundles.

**Review by isaachinman — APPROVED** [review]

**Comment by isaachinman** [comment]
@stevejhiggs Happy for this to go in?

**Comment by stevejhiggs** [comment]
Yep, all happy on my side

**Comment by RA80533** [comment]
What were the thoughts on placing these files in the root directory as opposed to a build directory, etc.? Furthermore, were these files meant to be tracked in Git? Conventionally, source code is tracked in Git while the build files are not while the opposite is true for npm publication.

**Comment by isaachinman** [comment]
@RA80533 I don't take your point. None of the files in this PR are build files. You can see which files we ship via npm [here](https://www.npmjs.com/package/next-i18next), on the "Explore" tab.

**Comment by RA80533** [comment]
This change concerns moving the folder that contains the types to the dist folder, yes?

**Comment by RA80533** [comment]
serverSideTranslations.js and serverSideTranslations.d.ts are at the root directory and in dist.

**Comment by isaachinman** [comment]
That is because `serverSideTranslations` is imported from the root:

```tsx
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
```

Open to any suggestions that support all ECMAScript targets.

**Pull request merged**
