### PR TITLE
feat: Validate defaultNS exists via fs

### LINKED ISSUE #358: Server rendered markup is empty if you don't have a `common` namespace.
## Describe the bug
After adding next-i18next to my Next app, I noticed that the HTML source returned from the server didn't contain my app's markup. Specifically, `<div id="__next"></div>` was empty in the markup. When viewed in the browser, it rendered fine because the JS execution would construct the views via DOM manipulation, but I'd be missing out on the benefits of SSR.

After a bit of digging, I traced it back to the [`<NextStaticProvider />` component](https://github.com/isaachinman/next-i18next/blob/master/src/components/NextStaticProvider.js#L9), which does `return tReady ? children : null`.

And `tReady` is provided by [react-i18next's useTranslation hook](https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L38-L40), which checks if all relevant namespaces have been loaded.

The issue is that the list of namespaces ends up coming from `i18n.options.defaultNS`, and next-i18next sets `defaultNS` to `common` by default. My app doesn't have a `common` namespace, so `tReady` would never be true during SSR.

I appreciate that you've documented the default values of next-i18next options. However, what was missing for me was that `defaultNS` would determine whether there's server rendered markup or not. In addition, users might not realize that SSR is broken because client-side render works. 

## Occurs in next-i18next version
`0.43.0`

## Steps to reproduce
* Create a new next-i18next app as described in the README
* However, instead of having `common.json` in each language directory, have something else, for example `strings.json`
* Start the next dev server, load a page, then view source
* Notice that markup doesn't contain app view code
* Modify i18n config `defaultNS` to be `[]` or `["strings"]`
* Restart dev server, load page, view source
* Notice that markup *does* contain app view code

## Expected behaviour
I'm not really sure the best path forward. If you want to maintain that default value, users should be guided to either use a common.json translation file, or change the `defaultNS` option to suit their project. If you want the project to just work out of the box for all users, then `defaultNS`'s default value should be `[]` instead of `common`. Or perhaps it'd be better to throw if the default namespace doesn't exist in the project. That way the error would be surfaced more obviously.

If anything, this issue can serve as guide for anyone else who runs into this problem.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: Mac
 - Browser: Chrome (version won't matter)

### PR DESCRIPTION
**Pull request by isaachinman**
Fixes #358.

### CODE REVIEW

**Comment by radeno** [comment]
This PR breaks custom path for server side locales.
As i said in another Issue, nexti18next should respect `dir` for SSR from NextJS

**Comment by isaachinman** [comment]
@radeno Can you explain what you mean in detail?

**Comment by radeno** [comment]
https://github.com/isaachinman/next-i18next/blob/50276b8f576bfb77399c3a7eb765c0577423aa9f/src/config/create-config.js#L37

Doesn't respect custom settings for `options.backend`

**Comment by isaachinman** [comment]
I do not understand your point, please either explain in detail or submit your own PR with desired changes.

**Comment by radeno** [comment]
Your solution doesn't work anymore
https://github.com/isaachinman/next-i18next/issues/328#issuecomment-499008251 because you are check for defaultNS in same way.

**Comment by isaachinman** [comment]
Sorry, what does `config.backend` have to do with `config.defaultNS`? Feel free to set `defaultNS` to an empty array, or whatever you want.

**Comment by radeno** [comment]
Do you see your code i have posted? You are checking for DefaultNS file before `config.backend` is processed. So it always break, because file doesn't exist.

**Comment by isaachinman** [comment]
If `defaultNS` is a string, we will check the filesystem for it. Feel free to either:

1. Set `defaultNS` to an empty array, or whatever you want
2. Submit an enhancement PR with the functionality you desire

**Comment by radeno** [comment]
And in your comment i have linked, you recommends to make own paths. But that paths are not used.

**Pull request merged**
