### PR TITLE
fix: Respect user-defined prefix/suffix when looking for default NS

### LINKED ISSUE #1090: LocaleStructure not compatibility single brackets for namespace
## Describe the bug
I faced localeStructure and interpolation problem
my json is for variables with single brackets. 
like this
`"test": "Why {appName}?",`
and i used in code 
`{t("test", { appName: process.env.NEXT_PUBLIC_APP_NAME })}`

in the config it was stated that

```
localeStructure: "{lng} / {ns}",
    interpolation: {
        prefix: "{",
        suffix: "}",
    },
```
now such an entry does not work, I looked in the code and found that in
`node_modules/next-i18next/dist/commonjs/config/createConfig.js`
you are doing a replacement
`var defaultLocaleStructure = localeStructure.replace ('{{lng}}', lng) .replace ('{{ns}}', defaultNS);`
If you change it to single brackets or add an entry, then everything will work.
## Occurs in next-i18next version
8.1.2

## Steps to reproduce
like this. Use single brackets in common.json
`"test": "Why {appName}?",`
and i used in code 
`{t("test", { appName: process.env.NEXT_PUBLIC_APP_NAME })}`

## Expected behaviour
Expected result, that i can use single or more brackets for localeStructure and interpolation
## OS (please complete the following information)

MacOS 
Chrome 89.0.4389.90

### PR DESCRIPTION
**Pull request by alexmchardy**
Fixes #1090 by respecting any custom `interpolation.prefix` and `interpolation.suffix` while using `localeStructure` to see if the default namespace file exists.

Can be tested by changing `/examples/simple/next-i18next.config.js` to
```
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
  interpolation: {
    prefix: '%{',
    suffix: '}',
  },
  localeStructure: '%{lng}/%{ns}',
}
```

Before the change, this config would result in this error:
```
Error: Default namespace not found at public/locales/%{lng}/%{ns}.json
```

After the change, the error goes away and interpolations work as expected. (To verify that interpolations work, you need to change `/examples/simple/public/locales/en/common.json` to use the `%{` `}` prefix and suffix.)

### CODE REVIEW

**Comment by devan-huapaya** [comment]
Can this be merged? @isaachinman <3

**Comment by isaachinman** [comment]
Hey @alexmchardy @devan-huapaya – sorry for the delay.

This PR looks great, it just needs test coverage. Thanks!

**Comment by devan-huapaya** [comment]
No worries @isaachinman  I'm just a random who was hoping to use the prefix setting!

I was able to get around the issue by wrapping useTranslation in it's own hook and adding 
`interpolation: { prefix: '[[', suffix: ']]' }` to all hook calls when options were passed in

**Comment by alexmchardy** [comment]
@isaachinman added a test, hopefully looks good.

cc. @devan-huapaya

**Review by isaachinman — APPROVED** [review]

**Pull request merged**
