### PR TITLE
chore: Drop Babel to compile the package with tsc

### PR DESCRIPTION
**Pull request by martpie**
**This is an exploration** more than a hard wish to see this merged.

Background story: we're making a lot of use of `next-i18next` at my company. We are creating a new boilerplate to start our projects, and this package is part of it.

We try to not pollute bundles too much, and there I saw this:

Screen Shot 2020-03-30 at 12 55 47

Related to https://github.com/isaachinman/next-i18next/issues/152 and https://github.com/isaachinman/next-i18next/issues/580

So I had a look, and saw you were building the package with Babel, which was including polyfills for you.

It felt a bit weird for me, as the packaged should already be transpiled to IE 11 code without adding polyfills by itself.

As some parts of the packages are TypeScript, I tried to figure out what could be the downside of dropping Babel and the TypeScript Compiler instead, while targeting ES3 for the default export (could be ES5 too I guess).

Here's a first draft. Everything seems to be working except one test that broke (related to Classes).

Now my question is: should I keep investing time in this direction to remove the need for `core-js@2` (Next.js comes with its own polyfill system now too, since 9.3)? Or is it something you are not considering/feel is not the right approach?

I may be missing some part of the story here.

Anyway, if this is something you're not interested into, I'll just close the PR.

### CODE REVIEW

**Comment by isaachinman** [comment]
> It felt a bit weird for me, as the packaged should already be transpiled to IE 11 code without adding polyfills by itself.

Not sure what you mean by this. We can transpile to an ECMAScript target, but there are specific language features which vary in support - that's the point of the polyfills in this case.

In general I do not hold strong opinions about the build process. The only requirement is that `next-i18next` fully maintains the same level of browsers support that NextJs does, and last I checked this included IE11.

**Comment by martpie** [comment]
> but there are specific language features which vary in support

do you have a concrete example? 🤔

**Comment by isaachinman** [comment]
@martpie It's been awhile since I worked in this space, but I would suggest you just clone the repo, remove `corejs` and `useBuiltIns`, run the example app in prod mode, and see what breaks in IE11.

As a side note, the `es` target is specifically provided for people that want to opt out of this build process and would rather consume "current NodeJs" code and/or transpile on their own.

**Comment by martpie** [comment]
> I would suggest you just clone the repo, remove corejs and useBuiltIns, run the example app in prod mode, and see what breaks in IE11.

sounds reasonable, I will try that!

**Pull request closed without merging**
