### PR TITLE
feat: added customClientLocalePath property

### PR DESCRIPTION
**Pull request by hochitom**
I'm currently working on a project where we're using next & next-i18next within a nx monorepo. and in this case we needed a custom path property to load the translation files in the client.

### CODE REVIEW

**Comment by isaachinman** [comment]
Hey @hochitom – not sure I understand the purpose of this PR. You can just modify the `localePath` config option itself to achieve this behaviour, that's what it's there for.

**Comment by hochitom** [comment]
yeah I know, my description was maybe a bit unclear. when working with nx monorepos, the destination of the locales is for example under `apps/somename/public/static/translations/en/common.json` which I need to configure with `localePath`. When doing this the client tries to load the files also from `apps/somename/public/static/translations/en/common.json` which in this case need to be just `/static/translations/en/common.json`. that's why we added this additional parameter to get nx + next + next-i18next working.

**Comment by isaachinman** [comment]
Still not sure I understand. It sounds like you just need to do:

```
localePath = typeof window === 'undefined' ? serverPath : clientPath
```

Is that the behaviour you are hoping for?

**Comment by hochitom** [comment]
you are totally right -> the new parameter is not necessary.

**Pull request closed without merging**
