### PR TITLE
fix(types): remove T from return types

### PR DESCRIPTION
**Pull request by prokopsimek**
Remove T from return types because it requires `t` function in props and it's not necessary.

before:
image

after:
image

pls check if it works for you @felixmosh

### CODE REVIEW

**Comment by isaachinman** [comment]
@felixmosh @kachkaev Mind having a look?

**Comment by felixmosh** [comment]
@prokopsimek it is not works with decorator usage.

**Comment by prokopsimek** [comment]
@felixmosh ok, could you please try this?

```
Subtract<T, I18nProps> & (T extends React.ComponentType<infer P> ? React.ComponentType<Subtract<P, I18nProps>> : never);
```

**Comment by felixmosh** [comment]
> ```
> Subtract<T, I18nProps> & (T extends React.ComponentType<infer P> ? React.ComponentType<Subtract<P, I18nProps>> : never);
> ```

It is not works, cause T is the component class type, not it's props

**Comment by prokopsimek** [comment]
> @prokopsimek it is not works with decorator usage.
> We can change the type of `I18nProps` and make `t` optional

@felixmosh It's not possible, because of the type checking. TypeScript throws an error `Cannot invoke an object which is possibly 'undefined'.ts(2722)` where I call `props.t('more')`

**Comment by prokopsimek** [comment]
I have found the problem. It's because my component `extends React.SFC<T>` and it makes return type of `withNamespaces(...): T & never` instead of the Subtract.

**Comment by felixmosh** [comment]
> > @prokopsimek it is not works with decorator usage.
> > We can change the type of `I18nProps` and make `t` optional
> 
> @felixmosh It's not possible, because of the type checking. TypeScript throws an error `Cannot invoke an object which is possibly 'undefined'.ts(2722)` where I call `props.t('more')`

How is that related to type checking? this is a runtime error.
If we convert `t` to be optional this will solve the issue of requirement of `t` prop.

**Comment by prokopsimek** [comment]
> > > @prokopsimek it is not works with decorator usage.
> > > We can change the type of `I18nProps` and make `t` optional
> > 
> > 
> > @felixmosh It's not possible, because of the type checking. TypeScript throws an error `Cannot invoke an object which is possibly 'undefined'.ts(2722)` where I call `props.t('more')`
> 
> How is that related to type checking? this is a runtime error.
> If we convert `t` to be optional this will solve the issue of requirement of `t` prop.

@felixmosh I have set `"strictNullChecks": true`

**Comment by felixmosh** [comment]
Ha, sorry then :)

Maybe we will go to a different approach, by using overloading, maybe we can declare 2 interfaces, that will work in both of the scenarios

**Comment by prokopsimek** [comment]
@felixmosh Have you tried to use react-i18n's decorators and not only next-i18next's decorators? Because I haven't seen some examples of how to use react-i18n's functions as decorators. Is it common to use it this way in react-i18n?

**Comment by felixmosh** [comment]
@prokopsimek, yes I'm using it as a decorator for 2 years already

**Comment by isaachinman** [comment]
Let me know when this is ready to go and I'll review it.

**Comment by felixmosh** [comment]
@prokopsimek lets drop the decoration types for now, I can't find any proper way to support both, and decorators are proposal, so I will handle it in my app.

**Comment by AppliftingHQ** [comment]
@felixmosh nope

this works for me:

```typescript
withNamespaces(
    namespace: Namespace | NamespaceExtractor,
    options?: WithNamespacesOptions,
  ): <P>(
    component: React.ComponentType<P>,
  ) => React.ComponentType<Subtract<P, I18nProps>>;
```

**Comment by prokopsimek** [comment]
@felixmosh nope

this works for me:

```typescript
withNamespaces(
    namespace: Namespace | NamespaceExtractor,
    options?: WithNamespacesOptions,
  ): <P>(
    component: React.ComponentType<P>,
  ) => React.ComponentType<Subtract<P, I18nProps>>;
```

**Comment by kachkaev** [comment]
Do we need `I18nProps` as such ? Can we use `WithNamespaces` from `react-i18next` when subtracting? It contains genuine typings for `t` and other props, see https://github.com/isaachinman/next-i18next/pull/239#issuecomment-475916007 for context.

**Comment by prokopsimek** [comment]
@kachkaev it seems that we can :)

```
withNamespaces(
    namespace: Namespace | NamespaceExtractor,
    options?: WithNamespacesOptions,
  ): <P>(
    component: React.ComponentType<P>,
  ) => React.ComponentType<Subtract<P, WithNamespaces >>;
```

works for me

**Comment by prokopsimek** [comment]
@felixmosh @isaachinman So should I update the PR to merge it?

**Comment by isaachinman** [comment]
Update how? Just let me know when this is ready to go and I'll review it.

**Comment by prokopsimek** [comment]
@isaachinman As is the last my code snippet in comments. Instead of having working types for decorators.

**Comment by isaachinman** [comment]
Looks fine to me.

**Comment by kachkaev** [comment]
+1 for using `WithNamespaces` from `react-i18next` instead of `I18nProps`. This custom typing can be deleted as it's not used anywhere else.

**Pull request closed without merging**
