### PR TITLE
docs: Add readme note to inform about polyfill solution for browsers with restricted ES support.

### PR DESCRIPTION
**Pull request by StarpTech**

### CODE REVIEW

**Comment by isaachinman** [comment]
https://github.com/isaachinman/next-i18next/issues/290#issuecomment-488767289

**Comment by StarpTech** [comment]
This is temporary thing until the fix was implemented.

**Comment by isaachinman** [comment]
Polyfilling is not something which is specific to IE. I'll merge this as a temporary measure if the message can be more generic.

**Comment by StarpTech** [comment]
Propose something....

**Comment by isaachinman** [comment]
"Support for older browsers may require polyfills until #290 is resolved"

**Comment by StarpTech** [comment]
This is also not accurate. Edge is not old it's the default browser of every windows 10 installation. We only talking about ES compatibility.

**Comment by StarpTech** [comment]
"Support for browsers with limited support for modern ES6/7 features may require polyfills until #290 is resolved."

**Comment by isaachinman** [comment]
Sure, fair enough. Please give the PR a semantic title and I'll merge it.

**Pull request merged**
