### PR TITLE
get rid of unecessary i18next instances

### PR DESCRIPTION
**Pull request by adrai**
i18next setup now is simpler and fixes https://github.com/isaachinman/next-i18next/issues/1101

### CODE REVIEW

**Comment by kachkaev** [comment]
If there are two concurrent SSR renders and only one i18next instance, won’t the languages end up mixed?

**Comment by dcodus** [comment]
@adrai this is looking very promising

No memory leak after 5000 requests
Screen Shot 2021-03-29 at 3 22 04 AM

Server is stable
Screen Shot 2021-03-29 at 3 22 51 AM

SSR is behaving as expected as per your fix in 8.1.1

Screen Shot 2021-03-29 at 3 24 11 AM
Screen Shot 2021-03-29 at 3 23 49 AM

**Comment by adrai** [comment]
> If there are two concurrent SSR renders and only one i18next instance, won’t the languages end up mixed?

That's why I wanted to clone... same bahaviour like i18next-http-middleware 🤷‍♂️
But I don't know how next.js works behind the scene...

**Comment by adrai** [comment]
alternative: #1109

**Comment by isaachinman** [comment]
Yes, if this was used in `getServerSideProps` and encountered two concurrent reqs, we'd have issues. A singleton unfortunately won't solve our problem.

**Pull request closed without merging**
