### PR TITLE
refactor: Remove interpolation from defaultConfig

### LINKED ISSUE #1535: i18next formatters not applied to translation values
## Describe the bug
Unable to format translations with built in i18next formatters (currency, number etc)

## Occurs in next-i18next version
`9.1.0`

## Steps to reproduce
Example Repo: https://github.com/jacknevitt/next-i18next-no-format

## Expected behaviour
Translations with formats provided will display the translation with formatter applied. In the above repo, I expect to see "123" as "£123.00" for EN (GBP) and "123" as "€123.00" for DE (EUR).

## Screenshots
Not applicable

## OS (please complete the following information)
 - Device: MBP 2019 16"
 - Browser: Chrome 96.0.4664.55

## Additional context
There is no mention of formatters on the main readme for next-i18next. See https://www.i18next.com/translation-function/formatting#built-in-formats for i18next documentation.

### PR DESCRIPTION
**Pull request by isaachinman**
Fixes #1535

### CODE REVIEW

**Comment by jacknevitt** [comment]
Hey @isaachinman, do you know when this is expected to be released? Thanks

**Comment by isaachinman** [comment]
@jacknevitt @adrai Published via v10.0.0. Do you mind quickly validating that it's working as expected?

**Comment by jacknevitt** [comment]
Thanks! I am unavailable until the evening (UK time), I'll take a look then

**Comment by jacknevitt** [comment]
Apologies for the delay, I can confirm it's working. Thanks so much for getting this fix through!

**Pull request merged**
