### PR TITLE
Do not pass on withNamespaces props to Link

### LINKED ISSUE #97: Passing withNamespaces props into Next Link causes devtools warning
Spreading `props` in the `Link` component results in passing `withNamespaces` props down to Next.js' `Link` component, causing the following devtools warning:

screenshot from 2019-01-15 08-17-37

### PR DESCRIPTION
**Pull request by capellini**
Resolves #97.

### CODE REVIEW

**Comment by capellini** [comment]
Probably a good idea to use the `lng` prop that `withNamespaces` provides instead of [doing this](https://github.com/isaachinman/next-i18next/blob/7fbae9a3e765374a5310380662ab4315ae011bb2/src/components/Link.js#L34-L37) too, correct?

If you agree, I'll submit the PR.

**Comment by isaachinman** [comment]
Not sure about the `lng` prop - I'd need to look at that separately. Can you open an issue?

As far as this work - is there a simpler way to exclude properties from an object? This seems pretty verbose. Moreover I want to try and avoid getting into having to maintain this repo against `react-i18next` internals wherever possible.

**Comment by capellini** [comment]
> Can you open an issue?

:+1: See #99.

> is there a simpler way to exclude properties from an object?

There is a way that will probably require less maintenance, but is more verbose.  We could grab, the `propTypes` from Nest's `Link` component and extract values from `this.props` and only pass those on.

The problem is that Next `Link`'s `propTypes` are stripped in production (the good news is that the warning is removed, in production, too), so we would need code that would pass on all props if we cannot access `Link`'s `propTypes`, or pass just the `propTypes`if they are defined.

The good news is that this solution should eliminate the warning for good, even if `withNamespaces` or Next `Link` props change.

Would you rather that solution?

**Comment by capellini** [comment]
I submitted the proposed solution above as another commit in this PR.  The diffs of the two branches with `master` are below:
1. [Original solution diff](https://github.com/isaachinman/next-i18next/compare/7fbae9a..f033ef2)
2. [Using NextLink.propTypes solution](https://github.com/isaachinman/next-i18next/compare/7fbae9a..6159e73)

Let me know what you think when you get the opportunity.  If we decide to go with solution 2, I just need to add some more tests.

**Comment by isaachinman** [comment]
No, accessing another component's `propTypes` is an anti-pattern.

**Comment by isaachinman** [comment]
Fixed by f5fbdfc - I prefer this approach as I believe it's more maintainable going forward. Sorry to go back and forth on this. Thanks for bringing it up!

**Comment by capellini** [comment]
Ha!  Ok.  Whatever you say, boss. :smile:

**Comment by isaachinman** [comment]
Really sorry about that, I will try to not let it happen in the future. I'm very busy the past week (I'm sure you can tell by my slow responses).

**Comment by capellini** [comment]
No problem at all.  I'm very grateful to you that you have decided to make this open source.  I understand what a thankless job it is to maintain an open source package and am here to support you as much as possible, as I have a large project that I intend to use with this package in production.

If, by helping you get this production-ready, I can also help the developer community at large with another awesome open source project, so much the better!

I apologize if I seem pushy -- I'm just anxious to start using this in production ASAP.  Please let me know if there is any way that I can help relieve you of some of the burdens of maintaining this package.

In the meantime -- many thanks for all you do.

**Comment by isaachinman** [comment]
Your help has been immeasurable and has not gone unnoticed! This package has been well-received by both the i18n and Zeit core teams, so I hope we can keep it afloat.

I am trying to close smaller issues, but my main concern at the moment is setting aside a full hour or two to review #90.

**Comment by capellini** [comment]
> This package has been well-received by both the i18n and Zeit core teams

Excellent!

> but my main concern at the moment is setting aside a full hour or two to review #90.

I'm sure it goes without saying at this point, but should we miss anything in that PR, I stand ready to fix any bugs that may arise.  At the very least, I can say that it's working for my use case, but of course that should not preclude a thorough review on your part.  Let me know how I can help.

**Comment by isaachinman** [comment]
You are certainly keeping me busy. A lot of my time for this project is going to come at the weekend, so at this point I think I just require patience on your part.

After we get #90 merged, I will close all PRs (either via merge or actual closure), and undertake the TypeScript conversion on my own to prevent merge conflicts.

**Comment by capellini** [comment]
> You are certainly keeping me busy.

Well, to be fair, it's not exactly like I haven't also been putting in quite some time, too.

> A lot of my time for this project is going to come at the weekend, so at this point I think I just require patience on your part.

I'd like to think that I haven't pressured you and have been patient.  And I hope to continue to be so.

When I run into a problem or see something that may be improved, I submit an issue/PR.  When I see an issue in the issue tracker that I think I can help with, I submit a PR.  I do this all in an attempt to help you, not to add to your workload.  By all means, if you think I'm submitting too many PRs, please let me know and I will stop.

> After we get #90 merged, I will close all PRs (either via merge or actual closure), and undertake the TypeScript conversion on my own to prevent merge conflicts.

OK. I'll hold of on any new issues/PRs until post-Typescript conversion.

**Comment by isaachinman** [comment]
@capellini Very sorry if I came off as anything but appreciative. I value your contributions to this project and aim to take each issue/PR seriously.

And it's totally fine to open new issues, but probably best to hold off on actual PRs.

**Pull request closed without merging**
