### PR TITLE
$npm_execpath added, i18next to version 14.0.1

### PR DESCRIPTION
**Pull request by andylacko**
there is only 1 problem, husky fails to run :/ as if it doesn't recognize $npm_execpath

also, if you want this pull request, please check the version 14.0.1 of i18next

I don't have much time today, this is suggestion more than request

### CODE REVIEW

**Comment by isaachinman** [comment]
Can you please explain what the purpose of this PR is?

**Comment by lucasfeliciano** [comment]
@isaachinman I think it is because this project uses `yarn` to run scripts. 

And the `prepare` script runs even after `npm install`

Which means that who installs it as a dependency also needs to have `yarn` installed.

I would recommend to change all scripts on `package.json` to use npm since this is an open source library.

**Comment by lucasfeliciano** [comment]
@isaachinman I'm not worried about the maintainers, the point is use `npm` on scripts because of the users because the `prepare` script runs after you install `next-i18next` into any project.

So after `npm install next-i18next` it will run the prepare script with `yarn` but if the user doesn't have it it will fail.

**Comment by isaachinman** [comment]
This package doesn't need a `prepare` script for users to run, only a `prepublish` script. Last I checked they were deprecating certain scripts and it was a complete mess. The proper fix here would be to not have the end user run anything.

@lucasfeliciano Do you want to look into that?

**Comment by lucasfeliciano** [comment]
I can take a look at the end of the week

**Comment by isaachinman** [comment]
Basically, I think we need to change `prepare` to `prepublishOnly`.

I'm going to close this PR as we never got a response from @andylacko.

I've created #142 to track the npm scripts issue.

**Comment by andylacko** [comment]
ok, sure, sry, I was working the whole day, just wanted to help with npm/yarn 👌if it is only for developers, everybody can install yarn

**Comment by isaachinman** [comment]
No worries, I've already fixed #142 and will be publishing it soon.

**Comment by andylacko** [comment]
@isaachinman , btw nice job with that custom subpath, it works well.

I was wondering, if something like next/router middleware is included in bundle, or should I create it myself. Or meybe if it's on schedule, because I think it would be better, if I used library functions which are tested rather my own code. If it's not, I will create it for the project and afterwards I can give you the code, but don't know if I have time to study this repo and implement it proper way into lib

**Comment by isaachinman** [comment]
Hi @andylacko, I'm not sure I understand your question. Can you please open a new issue, clearly stating your question or request so that we can track the conversation separately?

**Pull request closed without merging**
