### PR TITLE
feat: Add useRouter and withRouter

### PR DESCRIPTION
**Pull request by isaachinman**
Continuation of #581.

### CODE REVIEW

**Comment by foxundermoon** [comment]
error when export

https://simple-chi.now.sh/second-page

https://simple-chi.now.sh/

**Comment by isaachinman** [comment]
Hi @foxundermoon, have you perhaps commented in the wrong place?

**Comment by foxundermoon** [comment]
@isaachinman 
not wrong place :)
I tested the pr.

**Comment by isaachinman** [comment]
@foxundermoon Okay, can you help us debug this and come up with a solution?

**Comment by foxundermoon** [comment]
@isaachinman I am hunting an i18n solution for next.js export static website.

I found it.   https://material-ui.com/  docs   https://github.com/mui-org/material-ui/tree/master/docs

translate query to the path prefix.
I'm not very familiar yet, I'm sorry I can't help now
```js
  exportPathMap: () => {
    const pages = findPages();
    const map = {};

    function traverse(pages2, userLanguage) {
      const prefix = userLanguage === 'en' ? '' : `/${userLanguage}`;

      pages2.forEach(page => {
        if (!page.children) {
          map[`${prefix}${page.pathname}`] = {
            page: page.pathname,
            query: {
              userLanguage,
            },
          };
          return;
        }

        traverse(page.children, userLanguage);
      });
    }

    // We want to speed-up the build of pull requests.
    if (process.env.PULL_REQUEST === 'true') {
      traverse(pages, 'en');
    } else {
      LANGUAGES_SSR.forEach(userLanguage => {
        traverse(pages, userLanguage);
      });
    }

    return map;
  },
```

**Comment by ortonomy** [comment]
Is there going to be any movement on this? It's become a critical need in one of my projects. 

What needs debugging? Where can I start helping?

**Comment by martpie** [comment]
Re-iterating on this, is there anything I can do more in order to have this available in official releases? :) it's something that is impacting my team right now and we start to have those weird mix of `next`'s `useRouter` and `import { router } from '../lib/next-i18next'`

**Comment by martpie** [comment]
@isaachinman would you feel more confident if this feature was enable-able behind an `experimental` flag? I could implement that

**Comment by isaachinman** [comment]
Hey @ortonomy and @martpie – sorry, the bulk of my work on this package has been to support serverless recently. I haven't had a chance to look at this PR in awhile now. I guess the place to start would be with a rebase against `master` and see what's working and what's broken. If either of you would be willing to lead the effort, that would be much appreciated.

**Comment by knyuwork** [comment]
I guess you also need to add `useRouter` under declare class of `NextI18Next` inside `types.d.ts`?

**Comment by isaachinman** [comment]
Yes, of course we'd need to export types.

**Comment by AXLLLOW** [comment]
Hi, can you clarify when the merge will be and how soon can I use it?

**Comment by isaachinman** [comment]
I will be releasing `next-i18next@beta` very shortly, which relies on NextJs internals for localised routing. Thus, this PR is obsolete.

**Pull request closed without merging**
