### PR TITLE
feat: Add an ESM entry point to allow better bundle optimizations

### PR DESCRIPTION
**Pull request by felixmosh**
tree-shaking & module concatenation

### CODE REVIEW

**Comment by isaachinman** [comment]
Sorry, how does this differ from the `es` target?

**Comment by felixmosh** [comment]
It only preserve the import / export syntax without rest of the "modern" syntax like it is in es version

**Comment by isaachinman** [comment]
Then it should target IE11, as that is NextJs' target.

**Comment by isaachinman** [comment]
Cool. My main concern here is if the addition of the `module` entry in `package.json` will cause some build systems to start grabbing that entrypoint instead of the `cjs` target.

I imagine we will need to release this on a major?

**Comment by felixmosh** [comment]
This is the main idea, webpack (or other bundlers) should use the `module` entry, because it is more bundle friendly

**Comment by isaachinman** [comment]
Well, I think we'll need to release it on the next major. Can you change the target and merge into the beta branch?

**Comment by felixmosh** [comment]
It is based on the beta version ;)

**Review by isaachinman — APPROVED** [review]

**Pull request merged**
