### PR TITLE
fix-848: Deep merge options.backend

### LINKED ISSUE #848: backend is not merged properly
## Describe the bug
When user providing `options.backend` it forces the user to provide default `loadPath` & `addPath`.

## Occurs in next-i18next version
6.0.3<

## Steps to reproduce
Provide only `options.backend.parse` option, the app won't find translation files

## Expected behaviour
It should use the default `loadPath` & `addPath` if none given by the user

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

## Additional context
Happens due to the fact that the deep merge [here](https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.ts#L120-L127) is not merging the `combinedConfig`  variable it self.

### PR DESCRIPTION
**Pull request by felixmosh**
Closes #848

### CODE REVIEW

**Review by isaachinman — APPROVED** [review]
While this does seem sensible, I think we'll need to release it on a major, as it is a breaking change.

**Comment by felixmosh** [comment]
Why is it a breaking change? pay attention to the order.... 
if the user do specify the `loadPath`, it will be the final value.
It just adds the `loadPath` & `addPath` if you didn't provide them.

(without them the app won't start)

**Comment by felixmosh** [comment]
@isaachinman ping

**Comment by felixmosh** [comment]
@isaachinman why this PR is not published as v7 major release?

**Comment by felixmosh** [comment]
Ping?

**Comment by isaachinman** [comment]
@felixmosh Do you want to change the target to the `next-v10` branch and get this merged into the beta before release?

**Comment by felixmosh** [comment]
@isaachinman sure, will do.

**Review by isaachinman — APPROVED** [review]

**Pull request merged**
