### PR TITLE
feat: Add typescript types

### PR DESCRIPTION
**Pull request by felixmosh**
I've added types for the module class.

image

image

### CODE REVIEW

**Comment by isaachinman** [comment]
Hey, thanks for this. One thing - `createConsoleLog` is not really exposed for end users. We probably want to remove that.

**Comment by felixmosh** [comment]
Cool, i will remove it :)

**Comment by isaachinman** [comment]
Thanks @felixmosh. Not sure if you saw #74, but that's our main goal. This is lightweight enough and maintainable in the meantime, but because we're not actually compiling anything, this could quickly become out of date.

**Comment by isaachinman** [comment]
Ah, one other thing - the Next and React types should be dev deps. Once we move those over, this is ready to merge.

**Comment by felixmosh** [comment]
@isaachinman done!

**Comment by felixmosh** [comment]
I've saw #74, as you said, my solution is a short-term solution :]

**Comment by hnq90** [comment]
@isaachinman Could you please release the new version which includes this commit?

**Comment by isaachinman** [comment]
@hnq90 This was merged an hour ago... Don't worry, a release will come soon.

**Comment by isaachinman** [comment]
Released in v0.34.0.

**Pull request merged**
