### PR TITLE
fix: Add a simple cache invalidation in dev mode

### PR DESCRIPTION
**Pull request by wasd171**
This pull request addresses https://github.com/isaachinman/next-i18next/issues/626

### CODE REVIEW

**Comment by isaachinman** [comment]
Ah, I wasn't expecting actual imperative use of `i18nextInstance.reloadResources`. I thought we were talking about cache invalidation and a hard browser reload?

**Comment by wasd171** [comment]
I meant that `i18n.services.resourceStore.data` acts as a certain cache and needs to be force updated on every network request while running in dev mode

**Comment by isaachinman** [comment]
So, a few thoughts: I'd like this to be a config-level option, eg `config.reloadResourcesDev` which is disabled by default. Also, I'd like the footprint of this option to be as small as possible. I think we can achieve this with a one liner in [the middleware](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.ts#L49), as `reloadResources` called without any args will reload all resources.

Finally, we'd need a couple tests to cover this. Thanks!

**Comment by wasd171** [comment]
I think that we can't put it in the middleware level. Imagine the following case: the developer
+ loads page A
+ navigates to page B
+ updates content of the page A
+ navigates back to page A
If we have it in the middleware, a force reload of the page will be needed, while having it in the `App.getInitialProps` would properly reload it automatically.

**Comment by isaachinman** [comment]
Those sort of considerations are why I am very hesitant to support this functionality in the first place. It needlessly complicates something that should probably just live in userland via `nodemon` anyways. This package never intended to support "live editing". Perhaps you could put together an add-on package and maintain that separately?

**Comment by wasd171** [comment]
I tend to disagree. This is a not an attempt to create a sophisticated hot reload solution but rather an attempt to provide an experience expected by default – page reload or navigation show the updated content. By moving it to the middleware level you on purpose hurt the developer experience and I cannot see a good reason why. What do you mean exactly when talking about a small footprint? Is it the number of lines (can be reduced but that would probably damage the readability of the code a bit) or the performance overhead (in this case we should not load all translations and namespaces – plus this also leads to the situations where it is possible for the developer to introduce bugs invisible on the dev but appearing on the prod)? I see a possibility to remove developers' confusion in 6 lines of code if we inline the `forceLoadNamespaces` function and 1 line if we really want to push it to the minimum.

Unfortunately this can't go to an add-on, I think that `next-i18next` does not support a plugin system of its own (correct me on this if I'm wrong) and the Next.js setup (`req.i18n` vs `this.i18n`) is too specific to be one of the `i18next` plugins.

**Comment by isaachinman** [comment]
> page reload or navigation show the updated content

Those are two separate things in a SPA. A "live reload" setup within a SPA that does not perform hard document requests is "sophisticated" in my book. I'd rather not have this feature touch the `app-with-translation` HOC, as the cognitive complexity therein is already too high.

To put it simply: if your use case requires reloading of translations from the filesystem in SPA navigation, you should probably just roll it yourself. The only real world use case I can see for that type of functionality is live editing.

**Comment by wasd171** [comment]
However you are already doing reloading of some translations in SPA navigation! Let's check the following case:
+ `examples/simple` is running
+ you go to the `index.js` page
+ update the `second-page.json`
+ navigate to the `second-page.js`
+ the SPA would load an updated `second-page.json`

Given that this behaviour is already present in the `app-with-translation` I do not see a reason to not update it to handle the case of the dev environment

**Comment by blake-mealey** [comment]
I definitely agree with @wasd171 - I have just started using this project and I found it very frustrating having to restart the server every time. I started using nodemon as a workaround but it's still a ton of overhead to see a simple change when Next.js has such a great dev experience otherwise.

**Comment by blake-mealey** [comment]
I can see the argument for making it config-level since not all users use NODE_ENV=production (although that seems to be pretty standard). It should be called out in the docs early on though so that it's easy for devs to find

**Comment by isaachinman** [comment]
I believe it'd be possible to write this as a one-liner via `i18n. reloadResources` in the HOC.

The goal of this package has never been to main a "great" dev experience on par with NextJs. I'm the sole maintainer and rely on contributions by the community, but am also very wary of scope creep. Using nodemon to restart your server when you change localisation content in development is a perfectly reasonable solution.

**Pull request closed without merging**
