### PR TITLE
docs: example app fixed for SSR #945

### PR DESCRIPTION
**Pull request by YuriGor**

### CODE REVIEW

**Comment by YuriGor** [comment]
PR recreated instead of #946

**Comment by isaachinman** [comment]
Strange, any idea why this is not being built on CircleCI?

**Comment by YuriGor** [comment]
No idea why, I am not using CircleCI, looks like it's not even trying. 
I see similar waiting status on other PRs so probably it's not related to code changes, but to infrastructure.
Is there any permissions configuration or filter? Like option to trigger build only for contributor?

I tried to run in from my account:
https://app.circleci.com/pipelines/github/YuriGor/next-i18next/1/workflows/76cd264b-4042-4272-8f58-187094da563b/jobs/1
But it tries to use some old npm and has some issue with package.lock file. Probably adding project is not as easy as just choosing repo from github and some additional configuration needed to make it run.

**Comment by isaachinman** [comment]
It should build automatically. May be a transient Circle error – try force pushing, or pushing an empty commit?

**Comment by YuriGor** [comment]
No effect, it just doesn't like me.

**Comment by isaachinman** [comment]
Not quite sure mate. It's working fine with #949 which I opened as a test, and other users' fork PRs have always built fine. You may need to enable CircleCI permissions on your forked repo itself.

**Comment by YuriGor** [comment]
Here is the same issue #835 
BTW my changes built succefully in my own cicle project:
https://app.circleci.com/pipelines/github/YuriGor/next-i18next?branch=master

**Comment by isaachinman** [comment]
I'm very close to releasing `next-i18next@beta`, which will make this PR obsolete, so I will just close it for now. Thank you @YuriGor!

**Pull request closed without merging**
