### PR TITLE
feat: Deep merge nested config options

### LINKED ISSUE #179: Deep merge nested config objects
We need to deep merge specific nested config objects, like `config.detection`, to make specifying single fields easier for users.

### PR DESCRIPTION
**Pull request by isaachinman**
Fixes #179.

### CODE REVIEW

**Comment by isaachinman** [comment]
@lucasfeliciano Mind taking a look at this, and seeing if it's what you had in mind?

@RonnyVo Mind taking a look at this, and seeing if setting just `config.detection.lookupCookie` now works for you?

**Comment by RonnyVo** [comment]
@isaachinman can you tell me how I can test before it get merged? Sorry I don't know much about about these workflow

**Comment by isaachinman** [comment]
@RonnyVo Probably the easiest way is:

1. Clone the repo, checkout this branch
2. Do `npm i && npm run build && npm link`
3. Go to your own project and do `npm link next-i18next`

**Comment by isaachinman** [comment]
@lucasfeliciano Yeah, that's right. I briefly considering pulling something like `deepmerge` in, but decided I'd rather this sort of deep merging be an intentional opt-in thing instead of all-encompassing.

**Pull request merged**
