### PR TITLE
feat: Custom localeSubpaths values

### LINKED ISSUE #279: Support regional locales
## Is your feature request related to a problem? Please describe.
In a current project we have a distinction between American english and Great Britten english. It seems that if I add the language 'en-GB' and serverLanguageDetection is true and my browser primary language is 'en-GB' that it will select 'en' and not 'en-GB'

## Describe the solution you'd like
I would like to be able to support regional locales. Please let me know your thoughts about this feature.

### LINKED ISSUE #283: opt-out trailing slash in index page url
## Is your feature request related to a problem? Please describe.
Enabling the localeSubpaths, `www.example.com/zh` is redirected to `www.example.com/zh/` while `www.example.com/zh/any` wont be redirect to `www.example.com/zh/any/`
I would like to have a consistence pattern in the url format

## Describe the solution you'd like
Add a new config options.

## Describe alternatives you've considered
N/A

## Additional context
N/A

### PR DESCRIPTION
**Pull request by isaachinman**
Fixes #283. Fixes #279.

Note: breaking changes, will be released on a v1 major.

Review(s) welcome from anyone.

This changes the `localeSubpaths` option to something that looks like:

```jsx
new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['de'],
  localeSubpaths: {
    en: 'en',
    de: 'custom-german-subpath'
  }
})
```

Because the locale subpath string is provided by the user, we can remove a lot of extra logic that was previously necessary. This new approach should be a lot more sane and maintainable long term.

### CODE REVIEW

**Comment by BondoS** [comment]
@isaachinman Please excuse me to ask how to implement this after your new update?
https://github.com/BondoS/next-i18next-ex
my project urls are like 
domain.com/en-eg/
domain.com/ar-eg/
domain.com/en-kw/
domain.com/ar-kw/

Thank You

**Comment by isaachinman** [comment]
Please follow the documentation.

**Comment by EugeneHlushko** [comment]
@isaachinman can you please point where to set up trailing slash enforcement? i can see there was an util but its removed now from the source code

**Comment by isaachinman** [comment]
@EugeneHlushko It's been removed, as it doesn't belong in `next-i18next`. If you want that functionality, you'll need to write or import a simple middleware to accomplish it.

**Comment by EugeneHlushko** [comment]
@isaachinman got it, ty

**Comment by aralroca** [comment]
@isaachinman It's a pitty to lose this feature... I think that the trailing slash enforcement is used a lot... Btw; the docs needs to be updated because all the examples are with the trailing slash

**Comment by isaachinman** [comment]
@aralroca I agree it's a useful feature, but it does not logically belong in this repo. It should be a standalone, simple middleware. If you are interested, I can publish a package for that. But, I think there are already some options on npm.

I'll update the docs now.

**Pull request merged**
