### PR TITLE
docs: example app fixed for SSR #945

### PR DESCRIPTION
**Pull request by YuriGor**

### CODE REVIEW

**Comment by YuriGor** [comment]
- Sorry for my German, google translate used.
- Feel free to adjust app design changes

**Comment by isaachinman** [comment]
Hey, @YuriGor – can we just convert one of the existing components, without adding all this other UI/changes? I'd like to keep the simple example as simple as possible.

I think we could achieve an example by using the [Footer](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/components/Footer.js), no?

**Comment by YuriGor** [comment]
Most minimal change would be just this moving `i18n` from import to props and nothing more.
image
Maybe you would prefer to have only this change? 
This change already will save time for somebody, who will start development using example and will try to render current language, so we don't have to explicitly demonstrate how to render current lang on SSR page.

**Comment by isaachinman** [comment]
Yep, seems fine to me!

**Comment by YuriGor** [comment]
Ok, then it will be easier to close this PR and create new one.

**Pull request closed without merging**
